{{- if .Values.installCRDs -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-pre-hook-job
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-pre-hook-job
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-pre-hook-job
    namespace: {{ .Release.Namespace }}
{{- end -}}
